>>> sudo nano deploy.yaml  <<<

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: frontend
spec:
- strategy:
  - type: Rolling Update
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: mypod
      labels:
        app: frontend
    spec:
      containers:
      - name: my container
        image: nginx
        ports:
        - containerPort: 80


kubectl apply -f deploy.yaml
kubectl get deploy
kubectl get rs
kubectl get pods
