apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaSet
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: my container
        image: nginx
