
apiVersion: v1
kind: Service
metadata:
  name: my-webserver
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
